### ISSUE TITLE
Add some Vector helper functions

### ISSUE THREAD

**Issue by Vadinci** [LuckyKat/Bento#74]
Some static(?) functions to reduce redundancy in code dealing with vector maths

e.g.
`var vec = Vector2.fromRotation(angle, length);`
to replace
`var vec = new Vector2(Math.cos(angle)*length, Math.sin(angle)*length);`

and
`Vector2.copyInto(target, source);`
to replace
`target.x = source.x; target.y = source.y;`

The main motivation for this is that the current functions are fine for math, but all return a new Vector2 object (or modify the original). This means that in vector math hot spots, either a lot of Vectors are created and dereferenced in the same frame, or all the vector math resorts to double line manual maths:

```
diff.x = current.x - prev.x;
diff.y = current.y - prev.y;
```

In order to reduce both redundancy and memory overhead I think a set of `...Into(target, a, b)` functions would be benificial

**Comment by HernanZh** [comment]
Added in v1.2.0
